- 👋 Hi, I’m @Alfarro1927
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
Alfarro1927/Alfarro1927 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
Information and technology Not World internet network Via Whatsapp +6282140735942
